version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symplify/easy-coding-standard
    versions:
    - 7.0.2
    - 9.2.18
  - dependency-name: localheinz/composer-normalize
    versions:
    - 2.13.0
